name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Print Hello World
      id: print-hello-world
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 150
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PRINT-HELLO-WORLD_RESULTS: "${{steps.print-hello-world.outputs.result}}"
      with:
        runners: print-hello-world
