name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Ay Allahin adi
      id: ay-allahin-adi
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Ay Allahin adi
        setup-command: ''
        command: python3 hello.py
        input: ''
        expected-output: Hello, world!
        comparison-method: exact
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        AY-ALLAHIN-ADI_RESULTS: "${{steps.ay-allahin-adi.outputs.result}}"
      with:
        runners: ay-allahin-adi
